/*
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more
letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

https://leetcode.com/problems/find-the-difference/
*/

var findTheDifference = function(s, t) {
    let hash1 = {};
    let hash2 = {};
    
    for(let i = 0; i < s.length; i++) {
        let elem = s[i];
        if(elem in hash1) {
            hash1[elem]++;
        } else {
            hash1[elem] = 1;
        }
    }
    
    for(let i = 0; i < t.length; i++) {
        let elem = t[i];
        if(elem in hash2) {
            hash2[elem]++;
        } else {
            hash2[elem] = 1;
        }
    }
    
    for(let prop in hash2) {
        if(!(prop in hash1) || hash2[prop] > hash1[prop]) {
            return prop;
        }
    }
    return -1;
};
